opentelemetry-operator:
  manager:
    collectorImage:
      repository: "mirror.gcr.io/otel/opentelemetry-collector-contrib"
    featureGatesMap:
      operator.targetallocator.mtls: true
      operator.collector.targetallocatorcr: true
      operator.observability.prometheus: true


exporters: {}

receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 30s
        static_configs:
        - targets: [ '0.0.0.0:8888' ]
        metric_relabel_configs:
        - action: labeldrop
          regex: (id|name)
          replacement: $$1
        - action: labelmap
          regex: label_(.+)
          replacement: $$1

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: []
      exporters: [debug]
